#!/usr/bin/env ruby

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'python'
cookbook 'git'

cookbook "luigi-node",
  :path => "vendor/luigi-node"

cookbook "luigi-scheduler",
  :path => "vendor/luigi-node"

cookbook "cloudera",
  :path => "vendor/luigi-node"
