#!/usr/bin/env ruby

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'python'
cookbook 'git'

cookbook "luigi",
  :path => "vendor/luigi"

cookbook "cloudera-hadoop",
  :path => "vendor/cloudera-hadoop"
